
name: objc_build
version: 0.0.1
language: objc
description: "iOS 编译，默认使用模拟器编译，如果上传证书，编译并构建 ipa 包"
public: true
tags:
  - objc
  - build

# use exising template for input
inputs:
  - name: FLOW_IOS_COMPILE_WORKSPACE		
    editable: true		    
    desc_cn: ".xcworkspace 的文件名称 (选填)"		
    desc_en: ".xcworkspace file name (optional)"
    
  - name: FLOW_IOS_COMPILE_PROJECT		
    editable: true		
    desc_cn: ".xcodeproj 的文件名称 (选填)"		
    desc_en: ".xcodeproj file name (optional)"
    
  - name: FLOW_IOS_COMPILE_SCHEME		
    editable: true		
    desc_cn: "scheme 的名称 (选填)"		
    desc_en: "scheme name (optional)"
    
  - name: FLOW_IOS_COMPILE_CONFIGURATION		
    editable: true		
    desc_cn: "自定义的名称，或 Debug/Release"		
    desc_en: "Customized configuration name, or Debug/Release"

  - name: FLOW_IOS_EXPORT_METHOD
    editable: true
    desc_cn: "Xcode 打包方式(上传证书后有效)"
    desc_en: "how Xcode should export the archive"
    category: select
    options:
      - app-store=app-store
      - ad-hoc=ad-hoc
      - package=package
      - enterprise=enterprise
      - development=development
      - developer-id=developer-id
    default: development

    
outputs:

script_path: ./run.sh  
  
template: |  
  
  
