
name: objc_build
version: 0.0.1
language: objc
description: Objc build task
public: true
tags:
  - objc
  - build

# use exising template for input
inputs:
    
outputs:

script_path: ./run.sh  
  
template: |  
  
  
