
name: objc_build
version: 0.0.1
language: objc
description: Objc build task
public: true
tags:
  - objc
  - build

inputs:
  - name: FLOW_IOS_COMPILE_WORKSPACE		
    editable: true		    
    desc_cn: ".xcworkspace 的文件名称 (选填)"		
    desc_en: ".xcworkspace file name (optional)"
    
  - name: FLOW_IOS_COMPILE_PROJECT		
    editable: true		
    desc_cn: ".xcodeproj 的文件名称 (选填)"		
    desc_en: ".xcodeproj file name (optional)"
    
  - name: FLOW_IOS_COMPILE_SCHEME		
    editable: true		
    desc_cn: "scheme 的名称 (选填)"		
    desc_en: "scheme name (optional)"
    
  - name: FLOW_IOS_COMPILE_CONFIGURATION		
    editable: true		
    desc_cn: "自定义的名称，或 Debug/Release"		
    desc_en: "Customized configuration name, or Debug/Release"
    
outputs:

script_path: ./run.sh  
  
template: |  
  
  
